### ISSUE TITLE
Provide option for old-style feeds list -- unread feeds only

### ISSUE THREAD

**Issue by mcackay** [phantomfish/byline#11]
The previous version had a good folder/feed list behavior IMHO - allowing me to work through feed by feed in my own priority order; or browse all, or a sub-category of feeds.  The new version always shows ALL feeds which takes more effort to find a feed with current articles to work through.

Would like an option for the old style if possible.

**Comment by phantomfish** [comment]
I take your point but several users found the old interface confusing and the disclosure arrows were a bit "heavy" in terms of UI I think.
