### ISSUE TITLE
Toggle for sync on cellular

### ISSUE THREAD

**Issue by mcackay** [phantomfish/byline#12]
I want to be able to minimise my cellular usage, and so I always sync on Wifi before going out to a cafe to read my news. But Byline will then sync and use cellular data from time-to-time.

* "Add a checkbox in the settings which allows you to disable sync on cellular.
  * BUT if you refresh manually then it should use the current network (e.g. cellular)

Similarly, if you're trying to minimise your cellular use you probably don't want images/etc downloading unless you've specifically opted into this.

* Add a new setting 'Fetch images on cellular' 
* or, Show a placeholder image which you can click on to trigger an immediate download.

Note: if you click on a non-cached article link though, then you should probably let that proceed -- as it was a user-triggered action.

**Comment by phantomfish** [comment]
I'll add more fine-grained settings for automatic syncing ... both in terms of how often it should take place, and whether it should use cellular data.

There is already a "Use Cellular Data" option for caching (which includes images etc).
