### ISSUE TITLE
Wishlist: Cache all links?

### ISSUE THREAD

**Issue by mcackay** [phantomfish/byline#15]
Some articles i read have multiple links within them -- it would be pretty cool if I could pre-cache all of them overnight while in Wifi and wake up in the morning, go to cafe, and then have EVERY page i may want to click on cached and not need to use cellular data.

If implemented, it would be good to cache the important links first -- so when building the cache, prioritise the rss-item link first, then do a second parse through the RSS concent and cache the extra links, etc.

**Comment by phantomfish** [comment]
This could lead to caching a huge amount of data.... A tentative no, for now.
