### ISSUE TITLE
Article status (read/bookmarked) not synchronised between views

### ISSUE THREAD

**Issue by mcackay** [phantomfish/byline#17]
BYLINE VERSION: 5.0 (1.3)
DEVICE: iPhone 6 Plus

As shown in the following video - http://youtu.be/5_mDHOyS7B4 - the Read and Bookmarked status indicators don't appear to keep in sync between different views (e.g message listing versus article view), and there is a delay in the read indicator automatically being toggled when you view an article ... at times.

There's also general UI unresponsiveness/lag while a sync is in progress, and some unknown delay when the app starts up.

I note from other discussions that the whole database is scanned to analyse the number of items in the cache -- I wonder if while that is in progress, updates to the database are blocked.

**Comment by phantomfish** [comment]
Thanks for the video! Leaving the user interface unresponsiveness aside (you've created a separate issue for that), it is possible that while the background thread is busy (updating the database after a sync, or loading cache information), changes to the read/saved state of items won't be updated in the UI. This is not ideal — I'll make sure such changes are marked in the UI straight away, without waiting for the background thread to respond.
