### ISSUE TITLE
(Slightly) more verbose sync progress indicator

### ISSUE THREAD

**Issue by mcackay** [phantomfish/byline#2]
While understanding the desire to keep the interface as minimalist as possible for release, it would be useful to have a slightly more detailed sync indicator. Specifically:

**Some indication of progress:**
* Show percentage progress, if known -- e.g. **Syncing...(35%)**
* Alternatively, could include progress count -- e.g. **Syncing... (35 of 72)**

**Phase indication:**
If there are multiple 'phases' to the sync -- e.g. Syncing with Feedly, caching -- and you can't accurately amalgamate these into one percentage total -- then just spit them out:
* Syncing...
* Images (14 of 46)
* Articles (4 of 23)

**More detail in Beta**
Especially during the beta, it would be useful to have extra information on what the sync code is actually doing, so we can report better bugs. Perhaps the messages can be simplified later, if they prove confusing -- but I know that I personally, would rather have more detail: If you're waiting for your phone to sync before you leave a wifi network, you want to know what it's doing and how long it will take to finish :)  If you're not that kinda person, then you just won't bother looking ...

**Comment by phantomfish** [comment]
I will try to add a progress bar for syncing and see how that looks.

**Comment by mcackay** [comment]
Awesome. I hope this makes it -- as it would totally satisfy #21 (that I opened a moment ago).

**Comment by phantomfish** [comment]
This wouldn't satisfy #21 as it would only apply to syncing, not caching. I experimented with a progress bar for caching, but as caching can take a very long time (and may be suspended by the system due to various network/battery that I can't know about) this was intrusive.

**Comment by phantomfish** [comment]
I've decided not to implement this for now. It looks messy when syncing is brief, as it often is...
