### ISSUE TITLE
Cache status showing "0" items

### ISSUE THREAD

**Issue by mcackay** [phantomfish/byline#4]
If you force-quit the application and re-launch it, and go into the settings area -- the "Status" item under Caching shows "Cached 0 items".  If you wait a while (1-2 minutes), it then shows "Cached 9203 of 10180 items". 

As per our other discussions, it seems to be re-scanning to see what resources need caching -- but the UI display is a bit confusing.  Ideally change this text to "*Calculating*" or something.

**Comment by phantomfish** [comment]
Fixed. When Byline launches the caching status is calculated in the background, and in your case this is obviously taking a substantial amount of time. (I may be able to reduce that through optimisations later.) From the next beta this will display "Calculating..." until the cache has been processed for the first time.
