### ISSUE TITLE
Mechanism to refresh cached pages/view original page

### ISSUE THREAD

**Issue by mcackay** [phantomfish/byline#7]
Sometimes there's an error with cached page, or the content is simply stale - and so there needs to be a way to view the latest content.

From earlier discussions, I believe that when you view an 'uncached' article you are effectively adding it to the cache, and then displaying it. Is this correct?

* If so, rather than disabling/greying out 'forward' button in the article view, could this be replaced with a "Refresh" indicator?
* Alternatively, if viewing a cached page - can you add some kind of thin status bar/band along the top of the article with a text/link: "Cached 2 days ago. View Original >"

**Comment by phantomfish** [comment]
Byline consults the headers of every resource, which contain information about whether a resource should be cached and for how long. If the headers say it's time to refresh (or the resource shouldn't be cached) OR if it's more than a day old, we'll try to pull a fresh version from the network. This will then replace the previously cached resource.

Given that, I don't think there's a need for controls to manually refresh pages.
