### ISSUE TITLE
Visual indicator of "full-left-swipe" touch

### ISSUE THREAD

**Issue by mcackay** [phantomfish/byline#8]
I love the new swipe mechanism for browsing between articles, and getting back to the message list. e.g.
* Swipe from (near-)left = prev message
* Swipe from right = next message
* Swipe from left edge = back to message list   ("Full-left-swipe")
This is great for one-handed use, and very awesome. 

However sometimes it can be non-obvious that you've clicked a little too far to the left, and are triggering the full-left-swipe instead of prev/next.

It would be great to somehow differentiate this touch-zone.

* How about adding a light vignette that appears over the full left-edge of the screen when you put your finger down within the 'full-left-swipe' zone?  

I'm not 100% sure this will fix it, but it may give a more obvious indicator that you've clicked in the wrong place and give you a chance to abort the swipe before you complete it.

**Comment by phantomfish** [comment]
I think this is the kind of thing that becomes second nature after a little trial and error. I wouldn't want to change the visual effect of the "back" swipe as it's a standard system-wide behaviour. ...but the animations do look different when you start to swipe, and I think that's enough. Besides, if you do get it wrong, it's hardly a destructive behaviour!

**Comment by mcackay** [comment]
The issue is compounded by the UI unresponsiveness at the moment, so hopefully if that's fixed then there'll be less need to repeatedly swipe to make it move to the next article ... and accidentally trigger the 'back to list'. We'll see. I'll wait for another version or two and report back if there's still issues. Thanks.
